version: '2'

services:
  nginx:
    restart: always
    image: nginx:stable-alpine
    network_mode: "host"
    volumes:
      - ./conf.d:/etc/nginx/conf.d/default.conf
      - ./frontend/:/var/www/frontend/